export const up = async (knex) => {
  await knex("comments").insert([
    {
      content: "Be nice with me ihihihi :)",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 2,
      createdAt: new Date().toISOString(),
    },
    {
      content: "RT si t triste 😢😢",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 2,
      createdAt: new Date().toISOString(),
    },
    {
      content: "C le premié comantaire pour teste",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 1,
      createdAt: new Date().toISOString(),
    },
    {
      content: "apren le francais debile",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 1,
      createdAt: new Date().toISOString(),
    },
    {
      content: "vrm aprend vite perceque la c cho come dirai un twittos réel",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 1,
      createdAt: new Date().toISOString(),
    },
    {
      content: "T tro nul mdrrrrrrrr",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 4,
      createdAt: new Date().toISOString(),
    },
    {
      content: "re tourn chairché t fruit dan les arbe",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 4,
      createdAt: new Date().toISOString(),
    },
    {
      content: "poulé mafé",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 4,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Apran le fr !!!!!!!!!!",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content: "la tchétché lui reglera son conte",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content:
        "Achet lui des bon bon \u0026 c gagner mon amie (si non jsuis la tsais)",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Jpéfère les chiens connards",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 3,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Jvé pa te doné mon secre",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 6,
      createdAt: new Date().toISOString(),
    },
    {
      content: "tg connard",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 7,
      createdAt: new Date().toISOString(),
    },
    {
      content: "crari toi t'es bo",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 6,
      createdAt: new Date().toISOString(),
    },
    {
      content: "C tro mims 😘",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "crari toi t'es bo",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 6,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Hello à toi Jass 😁😁😁😁",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 9,
      createdAt: new Date().toISOString(),
    },
    {
      content: "crari toi t'es bo",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 6,
      createdAt: new Date().toISOString(),
    },
    {
      content: "C NUUULLL !!",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 9,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Chui sur tu sais meme pa faire de trikshot pd",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 9,
      createdAt: new Date().toISOString(),
    },
    {
      content: "la taille du crustacé",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 9,
      createdAt: new Date().toISOString(),
    },
    {
      content: "tema l'astuce de pédophile",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content: "SARTEK BARNABE TARTINE",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content: "je veux finir en couple pas au hebs",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 5,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Tua rasiste baril de ...",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 10,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Zemmour sauve nous",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 10,
      createdAt: new Date().toISOString(),
    },
    {
      content: "JEANNE AU SECOURS !",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 10,
      createdAt: new Date().toISOString(),
    },
    {
      content: "réel secre sombre",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 6,
      createdAt: new Date().toISOString(),
    },
    {
      content: "est-ce quue tu m'aaiiiiiiiiiiiiiiiiiiimes ?",
      publicationDate: new Date().toISOString(),
      user_id: 5,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Eske t'es bonne même pour m appeler bébou ?",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Je t'adooore ❤️❤️❤️❤️",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "tu et cringe blan person nou on accepte pas sa au congo",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Je jou deja a fortnite aec mon bebouuuuuu, kase toi",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Wesh trankil les gans 😡😡😡😡",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "jesper quil aime la frite 2 manioc",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 8,
      createdAt: new Date().toISOString(),
    },
    {
      content: "tu lui mets bien au fond",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 11,
      createdAt: new Date().toISOString(),
    },
    {
      content: "🦑🦑🦑🦑🦑",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 11,
      createdAt: new Date().toISOString(),
    },
    {
      content: "ilegal au congo toi merite tchétché",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 11,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Jojoka il a pas de cerveau par contre",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 12,
      createdAt: new Date().toISOString(),
    },
    {
      content: "a qui tu di chut trichppp respec afric1",
      publicationDate: new Date().toISOString(),
      user_id: 4,
      post_id: 12,
      createdAt: new Date().toISOString(),
    },
    {
      content:
        "toi ecoute moi ta daronne la grosse daronne la **** on va t'attraper au bas tu bat et on va te mêler moi et mes gars",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 12,
      createdAt: new Date().toISOString(),
    },
    {
      content: "dsl 😥😥😥",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 13,
      createdAt: new Date().toISOString(),
    },
    {
      content: "tkt jsuis une meuf chérie",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 13,
      createdAt: new Date().toISOString(),
    },
    {
      content: "PTDR T KI ?",
      publicationDate: new Date().toISOString(),
      user_id: 2,
      post_id: 14,
      createdAt: new Date().toISOString(),
    },
    {
      content: "DIS LEUR ma préféré c'est taki taki",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 14,
      createdAt: new Date().toISOString(),
    },
    {
      content: "❓❓❓❓❓😡😡😡😡",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 14,
      createdAt: new Date().toISOString(),
    },
    {
      content:
        "原子彈是美國反動派用來嚇唬人的紙老虎。這看起來很可怕，但事實並非如此：人民決定戰爭的結果，而不是一兩種新武器。",
      publicationDate: new Date().toISOString(),
      user_id: 8,
      post_id: 12,
      createdAt: new Date().toISOString(),
    },
    {
      content:
        "Россия, учитывая волю народов Крыма, высказанную на референдуме 16 марта, приняла решение признать Республику Крым суверенным и независимым государством.",
      publicationDate: new Date().toISOString(),
      user_id: 8,
      post_id: 14,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Heya Kurdek hebe wê Kurdistanek jî hebe Herbiji kurdistan",
      publicationDate: new Date().toISOString(),
      user_id: 8,
      post_id: 14,
      createdAt: new Date().toISOString(),
    },
    {
      content: "👀👀👀👀👀👀👀👀",
      publicationDate: new Date().toISOString(),
      user_id: 1,
      post_id: 16,
      createdAt: new Date().toISOString(),
    },
    {
      content: "qu est ce tu baragouine morey",
      publicationDate: new Date().toISOString(),
      user_id: 3,
      post_id: 16,
      createdAt: new Date().toISOString(),
    },
    {
      content: "Koment on phait pour lavoire ?!",
      publicationDate: new Date().toISOString(),
      user_id: 6,
      post_id: 15,
      createdAt: new Date().toISOString(),
    },
    {
      content:
        "CLIQUEZ SUR CE MESSAGE POUR M'ECRIRE DIRECTEMENT SUR WHATSAPP: +22962088956",
      publicationDate: new Date().toISOString(),
      user_id: 7,
      post_id: 15,
      createdAt: new Date().toISOString(),
    },
    {
      content: "T'as déjà UN GIGA CHIBRAAAAAAAAAAX",
      publicationDate: new Date().toISOString(),
      user_id: null,
      post_id: 13,
      createdAt: new Date().toISOString(),
    },
  ])
}

export const down = async (knex) => {
  await knex("comments").del()
}
